gateway:
  enabled: true
  dnsSuffix: "${gateway_dns_suffix}"
  certificate:
    enabled: true
    issuerRef:
      name: cluster-ca-issuer
      kind: ClusterIssuer
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: cluster-gateway
    namespace: envoy-gateway-system
    sectionName: kafka-listener
users:
  enableAdminUser: true    